/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.andy.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class header extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5883741002278417315L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"header\",\"namespace\":\"com.andy.avro\",\"fields\":[{\"name\":\"sndType\",\"type\":\"string\",\"doc\":\"Идентификации типа события и соответствующей ему схемы\"},{\"name\":\"sndVersion\",\"type\":\"string\",\"doc\":\"Версия схемы события\"},{\"name\":\"sndDate\",\"type\":{\"type\":\"long\",\"logicalType\":\"local-timestamp-micros\"},\"doc\":\"Дата отправки события источником\"},{\"name\":\"prevEvtID\",\"type\":\"string\",\"doc\":\"ID предыдущего события в потоке событий источника\",\"default\":\"NONE\"},{\"name\":\"signature\",\"type\":\"string\",\"doc\":\"системная подпись\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.LocalTimestampMicrosConversion());
  }

  private static final BinaryMessageEncoder<header> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<header> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<header> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<header> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<header> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this header to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a header from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a header instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static header fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Идентификации типа события и соответствующей ему схемы */
  private java.lang.CharSequence sndType;
  /** Версия схемы события */
  private java.lang.CharSequence sndVersion;
  /** Дата отправки события источником */
  private java.time.LocalDateTime sndDate;
  /** ID предыдущего события в потоке событий источника */
  private java.lang.CharSequence prevEvtID;
  /** системная подпись */
  private java.lang.CharSequence signature;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public header() {}

  /**
   * All-args constructor.
   * @param sndType Идентификации типа события и соответствующей ему схемы
   * @param sndVersion Версия схемы события
   * @param sndDate Дата отправки события источником
   * @param prevEvtID ID предыдущего события в потоке событий источника
   * @param signature системная подпись
   */
  public header(java.lang.CharSequence sndType, java.lang.CharSequence sndVersion, java.time.LocalDateTime sndDate, java.lang.CharSequence prevEvtID, java.lang.CharSequence signature) {
    this.sndType = sndType;
    this.sndVersion = sndVersion;
    this.sndDate = sndDate;
    this.prevEvtID = prevEvtID;
    this.signature = signature;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return sndType;
    case 1: return sndVersion;
    case 2: return sndDate;
    case 3: return prevEvtID;
    case 4: return signature;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      null,
      new org.apache.avro.data.TimeConversions.LocalTimestampMicrosConversion(),
      null,
      null,
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: sndType = (java.lang.CharSequence)value$; break;
    case 1: sndVersion = (java.lang.CharSequence)value$; break;
    case 2: sndDate = (java.time.LocalDateTime)value$; break;
    case 3: prevEvtID = (java.lang.CharSequence)value$; break;
    case 4: signature = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'sndType' field.
   * @return Идентификации типа события и соответствующей ему схемы
   */
  public java.lang.CharSequence getSndType() {
    return sndType;
  }


  /**
   * Sets the value of the 'sndType' field.
   * Идентификации типа события и соответствующей ему схемы
   * @param value the value to set.
   */
  public void setSndType(java.lang.CharSequence value) {
    this.sndType = value;
  }

  /**
   * Gets the value of the 'sndVersion' field.
   * @return Версия схемы события
   */
  public java.lang.CharSequence getSndVersion() {
    return sndVersion;
  }


  /**
   * Sets the value of the 'sndVersion' field.
   * Версия схемы события
   * @param value the value to set.
   */
  public void setSndVersion(java.lang.CharSequence value) {
    this.sndVersion = value;
  }

  /**
   * Gets the value of the 'sndDate' field.
   * @return Дата отправки события источником
   */
  public java.time.LocalDateTime getSndDate() {
    return sndDate;
  }


  /**
   * Sets the value of the 'sndDate' field.
   * Дата отправки события источником
   * @param value the value to set.
   */
  public void setSndDate(java.time.LocalDateTime value) {
    this.sndDate = value;
  }

  /**
   * Gets the value of the 'prevEvtID' field.
   * @return ID предыдущего события в потоке событий источника
   */
  public java.lang.CharSequence getPrevEvtID() {
    return prevEvtID;
  }


  /**
   * Sets the value of the 'prevEvtID' field.
   * ID предыдущего события в потоке событий источника
   * @param value the value to set.
   */
  public void setPrevEvtID(java.lang.CharSequence value) {
    this.prevEvtID = value;
  }

  /**
   * Gets the value of the 'signature' field.
   * @return системная подпись
   */
  public java.lang.CharSequence getSignature() {
    return signature;
  }


  /**
   * Sets the value of the 'signature' field.
   * системная подпись
   * @param value the value to set.
   */
  public void setSignature(java.lang.CharSequence value) {
    this.signature = value;
  }

  /**
   * Creates a new header RecordBuilder.
   * @return A new header RecordBuilder
   */
  public static com.andy.avro.header.Builder newBuilder() {
    return new com.andy.avro.header.Builder();
  }

  /**
   * Creates a new header RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new header RecordBuilder
   */
  public static com.andy.avro.header.Builder newBuilder(com.andy.avro.header.Builder other) {
    if (other == null) {
      return new com.andy.avro.header.Builder();
    } else {
      return new com.andy.avro.header.Builder(other);
    }
  }

  /**
   * Creates a new header RecordBuilder by copying an existing header instance.
   * @param other The existing instance to copy.
   * @return A new header RecordBuilder
   */
  public static com.andy.avro.header.Builder newBuilder(com.andy.avro.header other) {
    if (other == null) {
      return new com.andy.avro.header.Builder();
    } else {
      return new com.andy.avro.header.Builder(other);
    }
  }

  /**
   * RecordBuilder for header instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<header>
    implements org.apache.avro.data.RecordBuilder<header> {

    /** Идентификации типа события и соответствующей ему схемы */
    private java.lang.CharSequence sndType;
    /** Версия схемы события */
    private java.lang.CharSequence sndVersion;
    /** Дата отправки события источником */
    private java.time.LocalDateTime sndDate;
    /** ID предыдущего события в потоке событий источника */
    private java.lang.CharSequence prevEvtID;
    /** системная подпись */
    private java.lang.CharSequence signature;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.andy.avro.header.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.sndType)) {
        this.sndType = data().deepCopy(fields()[0].schema(), other.sndType);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.sndVersion)) {
        this.sndVersion = data().deepCopy(fields()[1].schema(), other.sndVersion);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.sndDate)) {
        this.sndDate = data().deepCopy(fields()[2].schema(), other.sndDate);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.prevEvtID)) {
        this.prevEvtID = data().deepCopy(fields()[3].schema(), other.prevEvtID);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.signature)) {
        this.signature = data().deepCopy(fields()[4].schema(), other.signature);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
    }

    /**
     * Creates a Builder by copying an existing header instance
     * @param other The existing instance to copy.
     */
    private Builder(com.andy.avro.header other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.sndType)) {
        this.sndType = data().deepCopy(fields()[0].schema(), other.sndType);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.sndVersion)) {
        this.sndVersion = data().deepCopy(fields()[1].schema(), other.sndVersion);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.sndDate)) {
        this.sndDate = data().deepCopy(fields()[2].schema(), other.sndDate);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.prevEvtID)) {
        this.prevEvtID = data().deepCopy(fields()[3].schema(), other.prevEvtID);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.signature)) {
        this.signature = data().deepCopy(fields()[4].schema(), other.signature);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'sndType' field.
      * Идентификации типа события и соответствующей ему схемы
      * @return The value.
      */
    public java.lang.CharSequence getSndType() {
      return sndType;
    }


    /**
      * Sets the value of the 'sndType' field.
      * Идентификации типа события и соответствующей ему схемы
      * @param value The value of 'sndType'.
      * @return This builder.
      */
    public com.andy.avro.header.Builder setSndType(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.sndType = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'sndType' field has been set.
      * Идентификации типа события и соответствующей ему схемы
      * @return True if the 'sndType' field has been set, false otherwise.
      */
    public boolean hasSndType() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'sndType' field.
      * Идентификации типа события и соответствующей ему схемы
      * @return This builder.
      */
    public com.andy.avro.header.Builder clearSndType() {
      sndType = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'sndVersion' field.
      * Версия схемы события
      * @return The value.
      */
    public java.lang.CharSequence getSndVersion() {
      return sndVersion;
    }


    /**
      * Sets the value of the 'sndVersion' field.
      * Версия схемы события
      * @param value The value of 'sndVersion'.
      * @return This builder.
      */
    public com.andy.avro.header.Builder setSndVersion(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.sndVersion = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'sndVersion' field has been set.
      * Версия схемы события
      * @return True if the 'sndVersion' field has been set, false otherwise.
      */
    public boolean hasSndVersion() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'sndVersion' field.
      * Версия схемы события
      * @return This builder.
      */
    public com.andy.avro.header.Builder clearSndVersion() {
      sndVersion = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'sndDate' field.
      * Дата отправки события источником
      * @return The value.
      */
    public java.time.LocalDateTime getSndDate() {
      return sndDate;
    }


    /**
      * Sets the value of the 'sndDate' field.
      * Дата отправки события источником
      * @param value The value of 'sndDate'.
      * @return This builder.
      */
    public com.andy.avro.header.Builder setSndDate(java.time.LocalDateTime value) {
      validate(fields()[2], value);
      this.sndDate = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'sndDate' field has been set.
      * Дата отправки события источником
      * @return True if the 'sndDate' field has been set, false otherwise.
      */
    public boolean hasSndDate() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'sndDate' field.
      * Дата отправки события источником
      * @return This builder.
      */
    public com.andy.avro.header.Builder clearSndDate() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'prevEvtID' field.
      * ID предыдущего события в потоке событий источника
      * @return The value.
      */
    public java.lang.CharSequence getPrevEvtID() {
      return prevEvtID;
    }


    /**
      * Sets the value of the 'prevEvtID' field.
      * ID предыдущего события в потоке событий источника
      * @param value The value of 'prevEvtID'.
      * @return This builder.
      */
    public com.andy.avro.header.Builder setPrevEvtID(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.prevEvtID = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'prevEvtID' field has been set.
      * ID предыдущего события в потоке событий источника
      * @return True if the 'prevEvtID' field has been set, false otherwise.
      */
    public boolean hasPrevEvtID() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'prevEvtID' field.
      * ID предыдущего события в потоке событий источника
      * @return This builder.
      */
    public com.andy.avro.header.Builder clearPrevEvtID() {
      prevEvtID = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'signature' field.
      * системная подпись
      * @return The value.
      */
    public java.lang.CharSequence getSignature() {
      return signature;
    }


    /**
      * Sets the value of the 'signature' field.
      * системная подпись
      * @param value The value of 'signature'.
      * @return This builder.
      */
    public com.andy.avro.header.Builder setSignature(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.signature = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'signature' field has been set.
      * системная подпись
      * @return True if the 'signature' field has been set, false otherwise.
      */
    public boolean hasSignature() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'signature' field.
      * системная подпись
      * @return This builder.
      */
    public com.andy.avro.header.Builder clearSignature() {
      signature = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public header build() {
      try {
        header record = new header();
        record.sndType = fieldSetFlags()[0] ? this.sndType : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.sndVersion = fieldSetFlags()[1] ? this.sndVersion : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.sndDate = fieldSetFlags()[2] ? this.sndDate : (java.time.LocalDateTime) defaultValue(fields()[2]);
        record.prevEvtID = fieldSetFlags()[3] ? this.prevEvtID : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.signature = fieldSetFlags()[4] ? this.signature : (java.lang.CharSequence) defaultValue(fields()[4]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<header>
    WRITER$ = (org.apache.avro.io.DatumWriter<header>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<header>
    READER$ = (org.apache.avro.io.DatumReader<header>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










